FROM openjdk:17-alpine 
VOLUME /tmp 
COPY target/GatewayService-0.0.1-SNAPSHOT.jar gateway-microservice.jar 
ENTRYPOINT ["java", "-Dspring.profiles.active=cont", "-jar", "gateway-microservice.jar"]
ENV server.port=8761
EXPOSE 8761