FROM openjdk:17-alpine 
VOLUME /tmp 
COPY target/DiscoveryService-0.0.1-SNAPSHOT.jar discovery-microservice.jar 
ENTRYPOINT ["java", "-Dspring.profiles.active=cont", "-jar", "discovery-microservice.jar"]
ENV server.port=8010
EXPOSE 8010