FROM openjdk:17-alpine 
VOLUME /tmp 
COPY target/GalleryService-0.0.1-SNAPSHOT.jar gallery-microservice.jar 
ENTRYPOINT ["java", "-Dspring.profiles.active=cont", "-jar", "gallery-microservice.jar"]
ENV server.port=8086
EXPOSE 8086