FROM openjdk:17-alpine 
VOLUME /tmp 
COPY target/UsersService-0.0.1-SNAPSHOT.jar users-microservice.jar 
ENTRYPOINT ["java", "-Dspring.profiles.active=cont", "-jar", "users-microservice.jar"]
ENV server.port=8085
EXPOSE 8085